server.port: 4000

spring:
  security:
    oauth2:
      client:
        registration:
          app:
            client-id: app
            client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
        provider:
          app:
            issuer-uri: http://localhost:9999/auth/realms/one